### ISSUE TITLE
Overflow when instantiating FixedPoint from integer, but not from hex string. 

### ISSUE THREAD

**Issue by FrancesoM** [Schweitzer-Engineering-Laboratories/fixedpoint#8]
# Description
```
#Given that 0x7b52 is 31570 why is that?

# This is fine
FixedPoint('0x7b52', signed=1, m=14, n=16, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)

# This overflows
FixedPoint(31570, signed=1, m=14, n=16, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)
```

# Steps to reproduce

```
# 0.3 in Q7.8 - both with standard python and fixedpoint lib
a = round ( 0.3*(2**8) ) #77
af = FixedPoint(0.3,signed=1,m=7,n=8)

# 1.6 in Q7.8 - both with standard python and fixedpoint lib
b = round ( 1.6*(2**8) ) #410
bf = FixedPoint(1.6,signed=1,m=7,n=8)

a*b
```
>> 31570
```
af*b
```
>> FixedPoint('0x7b52', signed=1, m=14, n=16, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)

`0x7b52` is `31570`
`log2(31570)` is `14.9` , hence 15 bits are necessary to represent it, not 14!

The correct behaviour is to have an overflow when 31570 is converted into Q7.8, and it happens correctly, but when the string "0x7b52" no warnings are shown.

# Environment

* Operating System: Windows
* Python version: python 3.8
* fixedpoint version (find in the output of `pip list`): 1.0.1

**Comment by zks0002** [comment]
When you use a string to initialize a FixedPoint object, it distributes the bits on both sides of the binary point, right justified. So 
`FixedPoint('0x7b52', 1, 14, 16, ...)` becomes 0b00000000000000.0111101101010010, as shown below (see [Integer and Fractional Bits](https://fixedpoint.readthedocs.io/en/latest/string-formatting.html#integer-and-fractional-bits) in the string formatting page for formatting hints):

```python
>>> ab = FixedPoint('0x7b52', signed=1, m=14, n=16, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)
>>> f"{ab:#0{ab.m+2}bm}.{ab:0{ab.n}bn}"
'0b00000000000000.0111101101010010'
```

However, when you initialize with an integer, it interprets the integer as only integer bits. So you are correct, that the `int` 31570 requires ceil(log2(31570)) = 15 bits to represent, however, you're only giving it 14 integer bits (with `m=14`), one of which is negatively weighted, which is why it overflows. If you initialize 31570 without constraining m or n, you can see what's going on:

```python
>>> x = FixedPoint(31570, signed=1)
>>> f"{x:#0{x.m+2}bm}.{x:0{x.n}bn}"
'0b0111101101010010.0'
```

In both initializations above, the bit pattern (0b0111101101010010 or 0x7b52) is the same, they just end up on different side of the binary point.

So 0.3 * 1.6 (both in fixed point) look like this:

```python
>>> af = FixedPoint(0.3,signed=1,m=7,n=8)
>>> bf = FixedPoint(1.6,signed=1,m=7,n=8)
>>> abf = af * bf
>>> abf
FixedPoint('0xc58154', signed=1, m=21, n=24, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)
>>> f"{abf:#0{abf.m+2}bm}.{abf:0{abf.n}bn}"
'0b000000000000000000000.110001011000000101010100'
```

If desired, `FixedPoint.trim` will remove superfluous/insignificant bits (i.e., trailing or leading zeros):

```python
>>> from fixedpoint import trim
>>> abf_trimmed = trim(abf)  # or abf.trim() if you want to modify abf iteself
>>> abf_trimmed
FixedPoint('0x3da9', signed=1, m=1, n=15, overflow='clamp', rounding='convergent', overflow_alert='error', mismatch_alert='warning', implicit_cast_alert='warning', str_base=16)
>>> f"{abf_trimmed:#0{abf_trimmed.m+2}bm}.{abf_trimmed:0{abf_trimmed.n}bn}"
'0b0.011110110101001'
```

These int/str initialization behaviors are documented here:
* [Initializing from an `int`](https://fixedpoint.readthedocs.io/en/latest/initialization.html#initializing-from-an-int)
* [Initializing from a `str`](https://fixedpoint.readthedocs.io/en/latest/initialization.html#initializing-from-a-str)
